<!DOCTYPE html>
<html>
<head>
	<title>Drew B. Dennis - Work History</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="Online resume or CV for Drew B. Dennis.">
	<meta name="keywords" content="HTML,HTML5,CSS,CSS3,XML,JavaScript,Web Designer,Web Design,Web Developer,PHP,Codeigniter,Laravel,BevennyCreations,CV,Resume,Drew,DrewDennis,Drew B. Dennis,Drew Dennis,PHP Developer,IT Consultant">
	<meta name="author" content="Drew B. Dennis">
	<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>
	<link href='assets/css/style.css' rel='stylesheet' type='text/css'>
</head>
<body class="lang-en ">

	<div id="main">
			<div id="photo">
			<img src="assets/img/153ba6_164574_2986758.jpg" alt="" />
		</div>
		<div class="header photo">
	
		<h1 id="title"><span class="c">Drew</span> Beverly Dennis</h1>
	<div class="basic-info section">
				<div class="set">
		
							<p class="address">
					<span class="value">
						c/o Claudia W. Broderick, Regional Human Resources Officer, FAO(UN) Regional Office for Africa<br>#2 Gamel Abdul Nasser Road, P. O. Box GP 1628 Accra, Ghana					</span>
				</p>
						<div class="r">
									<p class="email"><label>E-mail<span class="colon">:</span></label> <span class="value">drewbdennis@yahoo.com</span></p>
				
									<p class="website"><label>Website<span class="colon">:</span></label> <span class="value"><a href="https://www.facebook.com/drewbdennis" rel="nofollow">https://www.facebook.com/drewbdennis,</a> <a href="http://drewbdennis.com" rel="nofollow">http://drewbdennis.com,</a> <a href="https://bevennycreations.com" rel="nofollow">https://bevennycreations.com</a></span></p>
				
							</div>
			<div class="clear"> </div>
		</div><!-- set //-->
		<div class="clear"> </div>
	</div><!-- basic-info //-->

			</div><div class="clear"> </div>
	
		
			<div class="section section-work">
			<h2 class="title">Work experience</h2>
			<div class="set">
				<div class="item">
									<h3><span class="company l">IFAD-Mozambique</span>
							<span class="date r">March 20, 2018 &mdash; December 31, 2018</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">IT Consultant</span><div class="info"><span>Train CEDSIF staff, and hand over the 
overall management of the system(ArcaE) to the government. Support the 
finalization of the MoU between IFAD projects and CEDSIF on technical 
issues related to ArcaE.<br /><br />Train service provider on the use of the
 system. Do check and control on the first stage of uploading financial 
documents and documentations.<br /><br />Conduct quality tests on ArcaE for the pilot test of PROSUL.<br /><br />Provide technical support and capacity building to project staff.<br /><br />Organize and participate in the official launching of the e-archive (ArcaE) in partnership with government.<br /><br />Required
 to travel to project office across the country, in order to obtain the 
data of ArcaE for the migration to CEDSIF servers, as well as support on
 resolution of issues related to ArcaE.</span></div><div class="clear"> </div>
								</div>
				<div class="item">
					<h3><span class="company l">IFAD-Mozambique</span>
						<span class="date r">Mar 6, 2017 &mdash; Dec 31, 2017</span>
					</h3>
					<div class="clear"> </div>
					<span class="job_title">IT Consultant</span>
					<div class="info">1. Monitor the uptake of the electronic and archiving system ArcaE. Improve the system performance where need be, and conduct debug operations as scanning of documentation picks up at project sites. Simplify and design a more robust database as required. Test database and system for search-ability and implement any measures to guarantee easy access of information.<br />2. As Project Management Teams (PMTs) have expressed their preference in hiring specific teams to scan and upload the backlog of financial and procurement records, train these teams on the functionality of ArcaE. Provide best practices and devise<br />efficient procedures to accelerate this process. Revise ArcaE user manual accordingly.<br />3. Conduct quality tests on scanned documentation, once enough data has been uploaded. Specifically, quality tests should verify if the scanned documentation respects the requirement of image quality (200 dpi).<br />4. Support PMTs in connecting ArcaE servers to the world-wide-web, in order to guarantee secure access to the electronic archives through web browsers remotely. Test robustness of log-on system.<br />5. Design and operationalize the various reports to be generated by ArcaE.<br />6. From time to time, you will be required to travel to project offices across the country, in order to train project staff on maintenance and utilization of ArcaE, as well as support on resolution of issues related to ArcaE. Separate TORs will be provided for any field missions during this assignment.</div>
					<div class="clear"> </div>
				</div>
								<div class="item">
									<h3><span class="company l">IFAD-Mozambique</span>
							<span class="date r">Aug 22, 2016 &mdash; Nov 30, 2016</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">Consultant</span><div class="info">A. Support projects in establishing hardware requirements for the system.<br />B. Install and deploy ArcaE in all EU-supported projects headquarters, including the necessary access to the world-wide-web in order to guarantee secure connection from any geographical location.<br />C. Provide training and technical support during the initail upload of financial documentation to AcraE.<br />D. Finalize the ArcaE user manual, as well as archiving guidelines, detailing the optimal steps to be used for uploading financial documentation.<br />E. Support the projects in setting up automated backup capabilities for ArcaE and ensuring all required file systems and system data are successfully backed up to the appropriate media, recovery HDD, CD's and flash drives are created as deemed necessary, and the media recycled and sent off site as necessary.<br />F. Design and operationalize the various as per needed on the system.<br />G. Liaise with CFS on any Quality Assurance procedures to be implemented in order to guarantee compliance with IFAD guidelines on data storage/security.<br />H. Support projects on the security management functions and audits including monitoring all system access requests; validation of needs and evaluation of appropriate access levels needed for ArcaE system access.<br />I. Monitor ArcaE systems performancen on an on-going basis and up until end of initial adoption phase. Particular attention should be paid to quality and speed of remote access connection and system bugs that might be encountered.<br />J. Support the projects in the maintenance of the ArcaE servers and server operating systems at the project sites to applicable version levels.<br />K. Perform other duties that may be assigned by the Country Director from time to time.</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">IFAD-Mozambique</span>
							<span class="date r">Feb 2, 2016 &mdash; July 31, 2016</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">Consultant</span><div class="info">A. Showcase e-archiving system and resolve design issues<br />B. Test system at project site<br />C. Correct any bugs and system limitations<br />D. Write user manual and system tutorial<br />E. Workshop for presentation of e-archiving software</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">IFAD-Mozambique</span>
							<span class="date r">Dec 4, 2015 &mdash; Dec 31, 2015</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">Consultant</span><div class="info">A. Review of project supporting documentation<br />B. Preliminary report on status of project archiving<br />C. Proposal of filing and archiving system, including software solutions<br />D. Elaboration of action plan and budget<br />E. Development of guideline and manual<br />F. Filing and archiving training<br />G. Final Report</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">IFAD-Ethiopia</span>
							<span class="date r">Nov 2013 &mdash; December 2014</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">IT Support</span><div class="info">IT support to IFAD Supported Projects in Ethiopia<br />(Systems, Networking, Web Application Development, Softwares, Trouble Shooting, etc.)</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">TribeHired</span>
							<span class="date r">Dec 2012 &mdash; Aug 2013</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">PHP Developer</span><div class="info">Developing a social job seeking platform</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">Bevenny Creations</span>
							<span class="date r">Jan 2011 &mdash; Present</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">Founder and CEO</span><div class="info">Designing and building desktop or web applications using .net, php, html5, javascript, and mysql.</div><div class="clear"> </div>
								</div>
							
								<div class="item">
									<h3><span class="company l">Simply Computers</span>
							<span class="date r">Jan 2003 &mdash; Sept 2004</span>
								</h3>
								<div class="clear"> </div>
								<span class="job_title">Computer Repairs, Network Designer</span><div class="info">Computer repairs, Networking</div><div class="clear"> </div>
								</div>
							</div>
			<div class="clear"> </div>
		</div>
			<div class="section section-qualifications">
			<h2 class="title">Qualifications</h2>
			<div class="set">
							<div class="item">
								<span class="info"><p style="background:#FFFFFF;">Bachelor
of Science in Computer Security, (2011),
APIIT/UCTI. Kuala Lumpur, Malaysia.</p><p><span style="color:rgb(51,51,51);background-color:rgb(255,255,255);"><br /></span></p><p><span style="color:rgb(51,51,51);background-color:rgb(255,255,255);">Learning How to Learn: Powerful mental tools to help you master tough subjects by University of California, San Diego on Coursera. Certificate earned on July 18, 2016</span></p></span>
							</div>
						</div>
			<div class="clear"> </div>
		</div>
			<div class="section section-education">
			<h2 class="title">Education</h2>
			<div class="set">
						<div class="item">
							<h3><span class="course l">Bachelor of Science in Computer Security</span>
						<span class="date r">Jan 2008 &mdash; September 2011</span>
							</h3>
							<div class="clear"> </div>
							<span class="school">Asia Pacific University of Technology and Innovation (A.P.U)</span><div class="info"><p style="background:#FFFFFF;">Web Application: Built for a
courier company to manage and track shipments</p>

<p style="background:#FFFFFF;">Client/Server Application:
IRC chat interface that encrypts and decrypts data flowing from one client to
another using AES 256.</p>

<p style="background:#FFFFFF;">File
Encryption: places files in an encrypted container and
uses a passphrase along with AES 256.</p>

<p style="background:#FFFFFF;">Audio Steganography System:
encrypt and hide hidden message in audio stream. (.avi, .mp3, .wav)</p></div><span class="clear"> </span>
						</div>
						
						<div class="item">
							<h3><span class="course l">Learning How to Learn: Powerful mental tools to help you master tough subjects</span>
						<span class="date r">June 2016 &mdash; July 2016</span>
							</h3>
							<div class="clear"> </div>
							<span class="school">University of California, San Diego on Coursera</span><div class="info"><span style="color:rgb(51,51,51);background-color:rgb(255,255,255);">This course gives you easy access to the invaluable learning techniques used by experts in art, music, literature, math, science, sports, and many other disciplines. We’ll learn about the how the brain uses two very different learning modes and how it encapsulates (“chunks”) information. We’ll also cover illusions of learning, memory techniques, dealing with procrastination, and best practices shown by research to be most effective in helping you master tough subjects.  

Using these approaches, no matter what your skill levels in topics you would like to master, you can change your thinking and change your life. If you’re already an expert, this peep under the mental hood will give you ideas for: turbocharging successful learning, including counter-intuitive test-taking tips and insights that will help you make the best use of your time on homework and problem sets. If you’re struggling, you’ll see a structured treasure trove of practical techniques that walk you through what you need to do to get on track. If you’ve ever wanted to become better at anything, this course will help serve as your guide.</span></div><span class="clear"> </span>
						</div>
						</div>
			<div class="clear"> </div>
		</div>
			<div class="section section-interests">
			<h2 class="title">Interests</h2>
			<div class="set">
							<div class="item">
								<span class="info"><p>Hardware: Computer
repairs, Networking</p>

<p>Design Tools: Microsoft
Visio, Ms SQL, ASP.Net, PHP, MYSQL, Smart Draw</p>

<p>Computer: <br />
Operating System: MSDOS,
Microsoft Windows, Windows NT, Ubuntu, Fedora<br />
Design: Visual Studio.Net,
Aptana Studio 3<br />
Programming Language: VB.Net, C#, ASP.Net, PHP, JQuery, HTML5<br />
General: Microsoft Word,
Microsoft Excel, Microsoft Visio, Microsoft Powerpoint</p><p>Framework: Codeigniter, Laravel 5<br /></p><p>Sports: Basketball, swimming, hiking, biking, etc.</p></span>
							
							</div>
						</div>
			<div class="clear"> </div>
		</div>
		<div class="section section-references">
			<h2 class="title">References</h2>
			<div class="set">
				<div class="item">
					<span class="info">
						<span>Will be given when requested.</span>
					</span>
				</div>
			</div>
			<div class="clear"> </div>
		</div>
				
	</div>
	<div id="credit">Designed By: <a href="https://bevennycreations.com">Bevenny Creations</a></div>
	
</body>
</html>
